// ============================================================================
// THEME CONFIGURATION — QuantumDrop
// AUTO-GENERATED by /app/scripts/apply-theme.js  (site id: quantumdrop)
// Edit this file (or the source JSON at /app/themes/quantumdrop.json) to retheme.
// Tailwind colors are sourced from here at build time.
// ============================================================================

const theme = {
  "id": "quantumdrop",
  "siteId": "quantumdrop",
  "orderPrefix": "QTM",
  "brand": {
    "name": "QuantumDrop",
    "short": "Quantum",
    "legalName": "PT QUANTUM DROP DIGITAL"
  },
  "meta": {
    "title": "QuantumDrop | Premium Precision Top-Up",
    "description": "QuantumDrop — platform top-up game premium dengan presisi laboratorium. Engineered drop, calibrated delivery, untuk gamer yang menghargai akurasi.",
    "themeColor": "#5B6CFF"
  },
  "assets": {
    "heroBg": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920&q=80",
    "logo": "/logo-quantumdrop.svg"
  },
  "copy": {
    "hero": {
      "titleLine1": "Engineered Drop.",
      "titleLine2": "Calibrated Delivery.",
      "subtitle": "Top-up game dengan presisi laboratorium. Setiap transaksi dihitung, diuji, dan dikirim dengan akurasi atom — platform yang dibuat untuk gamer yang menghargai kualitas, bukan kebisingan.",
      "searchPlaceholder": "Calibrate: cari game, voucher, atau item..."
    },
    "features": [
      {
        "label": "Precision Delivery",
        "desc": "Akurasi 99.99%"
      },
      {
        "label": "Calibrated Pricing",
        "desc": "Harga teruji & adil"
      },
      {
        "label": "Lab-Grade Security",
        "desc": "Enkripsi research-tier"
      },
      {
        "label": "Concierge Support",
        "desc": "Dedicated 24/7"
      }
    ],
    "cta": {
      "titlePrefix": "Bergabung sebagai ",
      "titleHighlight": "Partner",
      "titleSuffix": "QuantumDrop",
      "subtitle": "Akses tier reseller premium dengan harga kalibrasi, dashboard analitik presisi, dan dukungan dedicated untuk skala bisnismu.",
      "button": "Mulai Konsultasi"
    },
    "footer": {
      "tagline": "Platform top-up game premium dengan presisi laboratorium. Untuk gamer dan reseller yang menghargai kualitas, bukan gimmick — QuantumDrop."
    }
  },
  "colors": {
    "primary": "#5B6CFF",
    "secondary": "#B8C0FF",
    "accent": "#E8D5B7",
    "background": "#0B0F1E",
    "card": "#141A33",
    "border": "#252C4A",
    "foreground": "#EDF0FF",
    "success": "#7DD3A8",
    "destructive": "#E85A6E",
    "gradientFrom": "#5B6CFF",
    "gradientTo": "#E8D5B7"
  },
  "fonts": {
    "display": "'Manrope', 'Geist', 'Inter', sans-serif",
    "body": "'Inter', 'Manrope', sans-serif",
    "mono": "'Geist Mono', 'JetBrains Mono', monospace",
    "googleFontsUrl": "https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap"
  },
  "style": {
    "heroVisual": "gold-orbs",
    "mascotGlow": "drop-shadow(0 0 20px rgba(91, 108, 255, 0.4)) drop-shadow(0 0 40px rgba(232, 213, 183, 0.25))",
    "heroAccent1": "bg-primary/15",
    "heroAccent2": "bg-accent/15"
  }
};

module.exports = theme;
