#!/usr/bin/env node
/**
 * apply-theme.js — Applies a theme preset (JSON) to a cloned site folder.
 *
 *   node apply-theme.js <site_dir> <theme_json_path> <site_id>
 *
 * Mutates:
 *   - <site_dir>/src/theme.config.js       (regenerated from JSON)
 *   - <site_dir>/src/index.css             (HSL :root vars only)
 *   - <site_dir>/public/index.html         (title, meta description, theme-color)
 *   - <site_dir>/package.json              (name)
 *
 * Tailwind colors auto-flow from theme.config.js (which tailwind.config.js
 * already requires()), so no patching needed there.
 */
const fs = require('fs');
const path = require('path');

// ---------- HEX → HSL ---------------------------------------------------------
function hexToHslComponents(hex) {
  let h = hex.replace('#', '').trim();
  if (h.length === 3) h = h.split('').map(c => c + c).join('');
  if (h.length !== 6) throw new Error(`Invalid hex: ${hex}`);
  const r = parseInt(h.slice(0, 2), 16) / 255;
  const g = parseInt(h.slice(2, 4), 16) / 255;
  const b = parseInt(h.slice(4, 6), 16) / 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  let hue = 0, sat = 0, lit = (max + min) / 2;
  if (max !== min) {
    const d = max - min;
    sat = lit > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: hue = (g - b) / d + (g < b ? 6 : 0); break;
      case g: hue = (b - r) / d + 2; break;
      case b: hue = (r - g) / d + 4; break;
    }
    hue *= 60;
  }
  return `${Math.round(hue)} ${Math.round(sat * 100)}% ${Math.round(lit * 100)}%`;
}

// ---------- Arg parsing -------------------------------------------------------
const [, , siteDir, themeJsonPath, siteId] = process.argv;
if (!siteDir || !themeJsonPath || !siteId) {
  console.error('Usage: apply-theme.js <site_dir> <theme_json_path> <site_id>');
  process.exit(1);
}

const theme = JSON.parse(fs.readFileSync(themeJsonPath, 'utf8'));

// ---------- 1. Generate theme.config.js ---------------------------------------
const themeConfigJs = `// ============================================================================
// THEME CONFIGURATION — ${theme.brand.name}
// AUTO-GENERATED by /app/scripts/apply-theme.js  (site id: ${siteId})
// Edit this file (or the source JSON at /app/themes/${siteId}.json) to retheme.
// Tailwind colors are sourced from here at build time.
// ============================================================================

const theme = ${JSON.stringify(theme, null, 2)};

module.exports = theme;
`;
fs.writeFileSync(path.join(siteDir, 'src/theme.config.js'), themeConfigJs);

// ---------- 2. Patch index.css :root HSL vars ---------------------------------
const cssPath = path.join(siteDir, 'src/index.css');
let css = fs.readFileSync(cssPath, 'utf8');

const c = theme.colors;
const hsl = {
  background:           hexToHslComponents(c.background),
  foreground:           hexToHslComponents(c.foreground),
  card:                 hexToHslComponents(c.card),
  primary:              hexToHslComponents(c.primary),
  secondary:            hexToHslComponents(c.secondary),
  border:               hexToHslComponents(c.border),
  accent:               hexToHslComponents(c.accent),
  destructive:          hexToHslComponents(c.destructive),
  gradientFrom:         hexToHslComponents(c.gradientFrom || c.primary),
  gradientTo:           hexToHslComponents(c.gradientTo || c.accent),
};

// Replace HSL in the :root block deterministically (line-based).
const replacements = [
  [/(--background:\s+)[\d.\s%]+(;)/,           `$1${hsl.background}$2`],
  [/(--foreground:\s+)[\d.\s%]+(;)/,           `$1${hsl.foreground}$2`],
  [/(--card:\s+)[\d.\s%]+(;)/,                 `$1${hsl.card}$2`],
  [/(--card-foreground:\s+)[\d.\s%]+(;)/,      `$1${hsl.foreground}$2`],
  [/(--popover:\s+)[\d.\s%]+(;)/,              `$1${hsl.card}$2`],
  [/(--popover-foreground:\s+)[\d.\s%]+(;)/,   `$1${hsl.foreground}$2`],
  [/(--primary:\s+)[\d.\s%]+(;)/,              `$1${hsl.primary}$2`],
  [/(--primary-foreground:\s+)[\d.\s%]+(;)/,   `$1${hsl.foreground}$2`],
  [/(--secondary:\s+)[\d.\s%]+(;)/,            `$1${hsl.secondary}$2`],
  [/(--secondary-foreground:\s+)[\d.\s%]+(;)/, `$1${hsl.background}$2`],
  [/(--muted:\s+)[\d.\s%]+(;)/,                `$1${hsl.border}$2`],
  [/(--accent:\s+)[\d.\s%]+(;)/,               `$1${hsl.accent}$2`],
  [/(--accent-foreground:\s+)[\d.\s%]+(;)/,    `$1${hsl.background}$2`],
  [/(--destructive:\s+)[\d.\s%]+(;)/,          `$1${hsl.destructive}$2`],
  [/(--border:\s+)[\d.\s%]+(;)/,               `$1${hsl.border}$2`],
  [/(--input:\s+)[\d.\s%]+(;)/,                `$1${hsl.border}$2`],
  [/(--ring:\s+)[\d.\s%]+(;)/,                 `$1${hsl.primary}$2`],
  [/(--gradient-from:\s+)[\d.\s%]+(;)/,        `$1${hsl.gradientFrom}$2`],
  [/(--gradient-to:\s+)[\d.\s%]+(;)/,          `$1${hsl.gradientTo}$2`],
  [/(\/\* THEME:)[A-Z_]+(\s\*\/)/,             `$1${siteId.toUpperCase()}$2`],
];
for (const [re, sub] of replacements) css = css.replace(re, sub);

// Update Google Fonts import line if custom fonts are provided
if (theme.fonts && theme.fonts.googleFontsUrl) {
  css = css.replace(/@import url\('https:\/\/fonts\.googleapis\.com[^']+'\);/,
    `@import url('${theme.fonts.googleFontsUrl}');`);
}

// Replace body font-family directive
if (theme.fonts && theme.fonts.body) {
  css = css.replace(/font-family:\s*'[^']+',\s*'[^']+',\s*sans-serif;/,
    `font-family: ${theme.fonts.body};`);
}

fs.writeFileSync(cssPath, css);

// ---------- 3. Patch public/index.html ----------------------------------------
const htmlPath = path.join(siteDir, 'public/index.html');
let html = fs.readFileSync(htmlPath, 'utf8');
html = html
  .replace(/<meta name="theme-color" content="[^"]*"\s*\/>/,
           `<meta name="theme-color" content="${c.primary}" />`)
  .replace(/<meta name="description" content="[^"]*"\s*\/>/,
           `<meta name="description" content="${theme.meta.description}" />`)
  .replace(/<title>[^<]*<\/title>/g,
           `<title>${theme.meta.title}</title>`);
fs.writeFileSync(htmlPath, html);

// ---------- 4. Update package.json name ---------------------------------------
const pkgPath = path.join(siteDir, 'package.json');
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
pkg.name = `site-${siteId}`;
fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');

console.log(`✓ Theme "${theme.brand.name}" applied to ${siteDir}`);
console.log(`  • Primary: ${c.primary}  Secondary: ${c.secondary}  Accent: ${c.accent}`);
console.log(`  • Title:   ${theme.meta.title}`);
